config/routes.rb
Rails.application.routes.draw do
  resources :levels
  resources :records do
    member do
      post 'level_update'
    end
  end
  resources :users 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#index'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#login'
  delete '/logout', to: 'sessions#destroy'

  get    '/loginnew',  to: 'sessions#loginnew'
  post   '/loginnew',  to: 'sessions#create_user'

  
end

app/models/record.rb
class Record < ApplicationRecord
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: %i[ show edit update destroy ]

# GET /records or /records.json
def index
  today = Date.today.strftime("%Y/%m/%d")
  @levels = Level.all
  @records = Record.all.order("recorded")
  @record_data = Record.new
  @user_data = User.find(session[:user_id])
  @login_user_records = @records.where( user_id:session[:user_id])
  @level_name = Level.find(@user_data.level_id).level_name
  @goal_step = Level.find(@user_data.level_id).goal_step
  @user_name = @user_data.nickname


  #今日の歩数
  @today_step = Record.find_by( user_id: session[:user_id], recorded: today)
  if @today_step.present?
    if @today_step.step > @goal_step
      @today_step2 = @goal_step
    else
      @today_step2 = @today_step.step
    end
  else
    @today_step = 0
    @today_step2 = 0
  end
 
  #５日分のデータの取得
  today_4 = (Date.today-4).strftime("%Y/%m/%d")
  days_ary = []
  achievement_5days = Record.where( user_id: session[:user_id], recorded: (today_4)..today)
  achievement_5days.each do | day_record |
    if day_record.step >= @goal_step
      days_ary << day_record.step
    end
  end
  @achievement_count = days_ary.count


  #順位
  bigginer_level = @levels.find_by(level_name: @level_name )
  bigginer_users = User.where( level_id: bigginer_level )
  today_records = []
  bigginer_users.each do |user|
    user_record = @records.find_by(user_id: user, recorded: today)
    today_records.push(user_record.step) if user_record
  end
  today_records.sort!.reverse!
  @entry = today_records.count
  @rank = today_records.index(@today_step.step)
  if @rank.present?
    #@rank = sprintf("%.2f", (10*@rank_number.to_f)/@entry.to_f)同率順位のとき順位が繰り上がらなかった
    @rank += 1
    #@rank_evaluation = 10-((@rank-1.00)/(@entry/10.0))　　　　　　　　　　#１０段階小数点以下切り捨て
    @rank_evaluation = sprintf("%.1f",10-((@rank-1.00)/(@entry/10.0)))  #１０段階小数点第２位以下切り捨て
  else
    @rank = 0
  end


  logger.debug("===================================================================================================")
  logger.debug(@level_name)
  logger.debug(@today_step.step)
  logger.debug(@today_step2)
  logger.debug(today_4)
  logger.debug(days_ary)
  logger.debug(bigginer_level)
  logger.debug(bigginer_users.count)
  logger.debug(today_records)
  logger.debug(@entry)
  logger.debug(@rank)
  logger.debug((@rank-1.00)/(@entry/10.0))
  logger.debug(@rank_evaluation)
  logger.debug(@user_name)
  logger.debug("===================================================================================================")
end

  # GET /records/1 or /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records or /records.json
  def create
    today = Date.today.strftime("%Y/%m/%d")
    @record = Record.where( user_id: session[:user_id], recorded: today)
    if @record.count == 0
      # 新しい日付で歩数を登録した場合
      @record = Record.new(record_params)
      @record.user_id = session[:user_id]
      @record.recorded = Date.today.strftime("%Y/%m/%d")
      if @record.save
        redirect_to records_path
      else
        render
      end
    else
      # 同じ日付で新しい歩数を登録した場合
      @record = Record.find_by( user_id: session[:user_id], recorded: today)
      @record.recorded = Date.today.strftime("%Y/%m/%d")
      if @record.update(record_params)
        redirect_to records_path
      else
        render
      end
    end
    # end
    
  end

  # PATCH/PUT /records/1 or /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to record_url(@record), notice: "Record was successfully updated." }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  def level_update
    if @level.update(level_params)
      format.html { redirect_to record_url(@record), notice: "Record was successfully updated." }
      format.json { render :show, status: :ok, location: @record }
    else
      format.html { render :edit, status: :unprocessable_entity }
      format.json { render json: @record.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /records/1 or /records/1.json
  def destroy
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url, notice: "Record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def record_params
      params.require(:record).permit(:user_id, :recorded, :step, :rank)
    end

    def level_params
      params.require(:level).permit(:goal_step, :level_stop, :level_name)
    end


end

app/views/records/_form.html.erb
<%= form_with(model: record) do |form| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <!-- <div class="field">
    <%= form.label :ユーザー名 %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :登録日 %>
    <%= form.datetime_select :recorded %>
  </div>  -->

  <div class="field">
    <%= form.label :歩数 %>
    <%= form.number_field :step %>
  </div>


 

  <div class="actions">
    <%= form.submit "登録" %>
  </div>

<% end %>

app/views/records/edit.html.erb
<h1>レコード編集</h1>

<%= render 'form', record: @record %>

<!--　<%= link_to '編集', @record %> -->

<!-- <%= link_to '詳細', @record %>  -->
<%= link_to '戻る', records_path %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>
<!doctype html>
<html lang="ja">
 
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

        <%= stylesheet_link_tag "records", :media => "all" %>
    </head>

    <body style="margin: 0 11% 0; ">
       <!-- モーダルを開くボタン -->
       <div class="container">
           <div class=" m-4 p-2  text-center bg-primary text-white" >
               <h1>✿ asterhealth ✿</h1>
           </div>

       </div>
       <!-- ボタンクリック後に表示される画面の内容 -->
       <div class="modal fade" id="testModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
           <div class="modal-dialog">
               <div class="modal-content">

                   <%= form_with(model: @record_data) do |form| %>


                       <div class="field">
                           <%= form.label :歩数 %>
                           <%= form.number_field :step %>
                       </div>


                       <div class="actions">
                           <%= form.submit "登録" %>
                       </div>


                   <% end %>


               </div>
           </div>
       </div>


       <div class="modal fade" id="testModal1" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
           <div class="modal-dialog">
               <div class="modal-content">

                   <%= form_with(model: @user_data) do |form| %>


                       <div class="field">
                           <%= form.label :難易度 %>:
                           <% @levels.each do | level | %>
                               <%= form.radio_button :level_id,level.id %><%= level.level_name %>
                           <% end %>
                       </div>


                       <div class="field">
                           <%= form.label :難易度の固定%>:
                           <%= form.radio_button :level_stop,"あり"%>あり
                           <%= form.radio_button :level_stop,"なし"%>なし
                       </div>


                       <div class="actions">
                           <%= form.submit "変更" %>
                       </div>
                   <% end %>
               </div>
           </div>
       </div>
       <div class="container my-3 py-2" >
           <table class="table container" style="max-width:280px; text-align: center;">
               <tr>
                   <th style="width: 10%"></th>
                   <th style="width: 40%">・名前</th>
                   <th style="width: 40%">
                       <%= @user_name %>
                   </th>
                   <th style="width: 10%"></th>
    
               </tr>
               <tr>
                   <th></th>
                   <th>・順位</th>
                   <th>
                       <%= @rank %>位
                   </th>
                   <th></th>
               </tr>
           </table>


           <table class="table container" style="max-width:460px; text-align: center;">
               <tr>
                   <th class="align-middle" style="width: 30%">
                       ・難易度
                   </th>
                   <th class="align-middle" style="width: 40%">
                       <%= @level_name %>
                   </th>
                   <th style="width: 30%">
                       <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#testModal1">難易度設定</button>
                   </th>
               </tr>
               <tr>
                   <th>
                       ・難易度の固定
                   </th>
                   <th>
                       <%= @user_data.level_stop %>
                   </th>
               </tr>
               <tr>
                   <th class="align-middle">
                       ・目標歩数
                   </th>
                   <th class="align-middle">
                       <%= @goal_step %>
                   </th>       
                   <th>
                       <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#testModal">歩数入力</button>
                   </th>
               </tr>
           </table>


           <table class="table container" style="max-width:700px; text-align: center;">
               <thead>
                   <tr>
                       <th style="width: 25%">歩数</th>
                       <th style="width: 50%">日時</th>          
                       <th style="width: 25%"></th>
                   </tr>
               </thead>
               <tbody>
                   <% @login_user_records.each do |record| %>
                       <tr>
                           <th>
                               <%= record.step %>
                           </th>
                           <th>
                               <%= record.recorded %>
                           </th>
                           <td>
                               <%= link_to '削除', record, method: :delete, data: { confirm: '本当に削除しますか？' } %>
                           </td>
                       </tr>
                   <% end %>
                </tbody>
            </table>
        </div>


        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <div >
           <h1 class=" px-5 py-1 text-center bg-info text-white">健康指数</h1>
       </div>
       <canvas id="myRaderChart"></canvas>
       <!-- CDN -->
       　<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
        <script>
           // alert(<%= @entry %>-<%= @rank %>)
           var ctx = document.getElementById("myRaderChart");
           var myRadarChart = new Chart(ctx, {
               type: 'radar',
               data: {
                   labels: ["歩数", "順位", "継続度"], //継続度は5日前から各レベルで何歩以上歩いたかを確認し、歩いた場合1を代入し合計で計算
                   datasets: [{
                       label: '<%= @user_name %>',
                       data: [(<%= @today_step2 %>/<%= @goal_step %>)*10 , <%= @rank_evaluation %>, (<%= @achievement_count%>/5)*10 ],
                       backgroundColor: 'RGBA(0,128,180, 0.5)',
                       borderColor: 'RGBA(0,128,180, 1)',
                       borderWidth: 3.5,
                       pointBackgroundColor: 'RGB(46,106,177)'
                   }]
               },
               options: {
                   title: {
                       display: true,
                       text: ''
                   },
                   scale:{
                       ticks:{
                           suggestedMin: 0,
                           suggestedMax: 10,       
                           stepSize: 2,
                           callback: function(value, index, values){
                               return  value +  '点'
                           }
                       }
                   },
                   maintainAspectRatio: false
               }
           });
       </script>
    </body>
</html>


<!-- 使わなくなるかも -->
<!-- <%= link_to "設定",levels_path %> -->

app/views/records/new.html.erb
<h1>新規作成</h1>

<%= render 'form', record: @record %>

<%= link_to '戻る', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ユーザー名:</strong>
  <%= @record.user_id %>
</p>

<p>
  <strong>登録日:</strong>
  <%= @record.recorded %>
</p>

<p>
  <strong>歩数:</strong>
  <%= @record.step %>
</p>



<%= link_to '編集', edit_record_path(@record) %> |
<%= link_to '戻る', records_path %>