config/routes.rb
Rails.application.routes.draw do
  resources :levels
  resources :records do
    member do
      post 'level_update'
    end
  end
  resources :users 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#index'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#login'
  delete '/logout', to: 'sessions#destroy'

  get    '/loginnew',  to: 'sessions#loginnew'
  post   '/loginnew',  to: 'sessions#create_user'

  
end

app/models/level.rb
class Level < ApplicationRecord
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: %i[ show edit update destroy ]

  # GET /levels or /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1 or /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels or /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to level_url(@level), notice: "Level was successfully created." }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1 or /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to level_url(@level), notice: "Level was successfully updated." }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1 or /levels/1.json
  def destroy
    @level.destroy

    respond_to do |format|
      format.html { redirect_to levels_url, notice: "Level was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def level_params
      params.require(:level).permit(:goal_step, :level_stop, :level_name)
    end
end

app/views/levels/_form.html.erb
<%= form_with(model: level) do |form| %>
  <% if level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
        <% level.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :階級 %>
    <%= form.radio_button :level_name,"初級"%>初級 
    <%= form.radio_button :level_name,"中級"%>中級 
    <%= form.radio_button :level_name,"上級"%>上級 
  </div>

  <div class="field">
    <%= form.label :目標歩数%>
    <%= form.number_field :goal_step %>
  </div>

  <div class="field">
    <%= form.label :難易度の固定%>
    <%= form.radio_button :level_stop,"あり"%>あり
    <%= form.radio_button :level_stop,"なし"%>なし
  </div>

  <div class="actions">
    <%= form.submit "登録" %>
  </div>

<% end %>

app/views/levels/edit.html.erb
<h1>「レベル」編集</h1>

<%= render 'form', level: @level %>

<%= link_to '詳細', @level %> |
<%= link_to '戻る', levels_path %>

app/views/levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>「レベル」</h1>

<table>
  <thead>
    <tr>
      <th>レベル</th>
      <th>目標歩数</th>
      <th>難易度の固定</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= level.level_name %></td>
        <td><%= level.goal_step %></td>
        <td><%= level.level_stop%></td>
        <td><%= link_to '詳細', level %></td>
        <td><%= link_to '編集', edit_level_path(level) %></td>
        <td><%= link_to '削除', level, method: :delete, data: { confirm: '本当に削除してもいいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規', new_level_path %>

app/views/levels/new.html.erb
<h1>新規作成</h1>

<%= render 'form', level: @level %>

<%= link_to '戻る', levels_path %>

app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>レベル:</strong>
  <%= @level.level_name %>
</p>

<p>
  <strong>目標歩数:</strong>
  <%= @level.goal_step %>
</p>

<p>
  <strong>難易度の固定</strong>
  <%= @level.level_stop%>
</p>

<%= link_to '編集', edit_level_path(@level) %> |
<%= link_to '戻る', levels_path %>